name: Notify Middleware and Await External Approval

on:
  workflow_dispatch:

jobs:
  notify-middleware:
    runs-on: ubuntu-latest
    outputs:
      environment_id: ${{ steps.get_env_id.outputs.environment_id }}
    steps:
      - name: Get GitHub Environment ID
        id: get_env_id
        run: |
          ENV_ID=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/environments/approval-required" \
            | jq -r '.id')

          echo "environment_id=${ENV_ID}" >> $GITHUB_OUTPUT

      - name: Notify Middleware
        run: |
          curl -X POST https://8046ed7ff9f9.ngrok-free.app/api/github/action \
            -H 'Content-Type: application/json' \
            -d '{
              "action_run_id": "${{ github.run_id }}",
              "environment_id": "${{ steps.get_env_id.outputs.environment_id }}",
              "project_id": "${{ github.event.repository.name }}",
              "payload": {
                  "Mudanca": "m1",
                  "Categoria": "cat",
                  "Subcategoria": "sub",
                  "T2R": "t2r",
                  "Nome_APP": "app",
                  "Repositorio_URL": "${{ github.event.repository.html_url }}",
                  "Namespace": "ns",
                  "CLUSTER": "cluster",
                  "Data_Inicio": "01/01/2024 10:00",
                  "Data_Termino": "01/01/2024 12:00",
                  "Grupo_Operador": "group",
                  "Origem": "origin",
                  "Descricao_Origem": "desc",
                  "Produto": "prod",
                  "autor": "Joao da Silva",
                  "email": "joao@silva.com",
                  "indisponibilidade": "Nao",
                  "impacto_parceiros": "Nao",
                  "impacto_financeiro": "Nao",
                  "PCI": "Nao"
              }
            }'

  await-approval:
    runs-on: ubuntu-latest
    needs: notify-middleware
    environment:
      name: approval-required
    steps:
      - name: Deployment (aguarda aprovação do middleware via API)
        uses: chrnorm/deployment-action@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: approval-required
